# Generated by Django 4.2.10 on 2026-02-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collector_approved',
            field=models.BooleanField(default=False),
        ),
    ]
