# Generated by Django 4.2.10 on 2026-02-09 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_collector_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('backup_contact', models.CharField(blank=True, max_length=32)),
                ('notification_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('inapp', 'In-app')], default='inapp', max_length=16)),
                ('preferred_days', models.CharField(blank=True, max_length=64)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=16)),
                ('trash_types', models.CharField(blank=True, max_length=64)),
                ('special_instructions', models.TextField(blank=True)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('landmark', models.CharField(blank=True, max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
