# Generated by Django 4.2.10 on 2026-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='release_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('released', 'Released'), ('failed', 'Failed')], default='scheduled', max_length=20),
        ),
    ]
