# Generated by Django 4.2.10 on 2026-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_pickup_release_reason_alter_pickup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='trash_type',
            field=models.CharField(choices=[('household', 'Household'), ('recyclable', 'Recyclable'), ('bulk', 'Bulk')], default='household', max_length=20),
        ),
    ]
