# Generated by Django 4.2.10 on 2026-02-08 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_add_ownership_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorapplication',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collectorapplication',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collectorapplication',
            name='ownership',
            field=models.CharField(choices=[('company', 'Company-owned'), ('personal', 'Personal / third-party')], default='personal', max_length=16),
        ),
        migrations.AlterField(
            model_name='collectorapplication',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('pickup', 'Pickup'), ('compactor', 'Compactor'), ('other', 'Other')], default='truck', max_length=32),
        ),
    ]
