# Generated by Django 4.2.10 on 2026-02-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_collectorapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectorapplication',
            name='status',
            field=models.CharField(choices=[('APPLICATION_SUBMITTED', 'Submitted'), ('APPLICATION_UNDER_REVIEW', 'Under review'), ('KYC_UNDER_VERIFICATION', 'KYC under verification'), ('KYC_VERIFICATION_FAILED', 'KYC verification failed'), ('APPLICATION_APPROVED', 'Approved collector'), ('APPLICATION_REJECTED', 'Rejected')], default='APPLICATION_SUBMITTED', max_length=32),
        ),
    ]
